
spring:
  application:
    name: cloud-fegin
server:
  port: 1300
eureka:
  client:
    service-url:
     defaultZone: http://127.0.0.1:1000/eureka/
# 开启fegin 的 hystrix 功能
feign:
  hystrix:
   enabled: true

# hystrix 熔断机制 设置服务超时时间
hystrix:
  command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 5000
